#!/usr/bin/env bash
#
# Rebuild the `deploy` branch from current `master` + concrete image tags.
#
# Inputs (env vars; any unset are read from existing deploy-branch state,
# then default to "latest" if no prior state exists):
#   ORY_CONSENT_TAG
#   ORY_INVITE_TAG
#   ORY_KRATOS_CONFIG_TAG
#   KRATOS_VENDOR_TAG
#   HYDRA_VENDOR_TAG
#   LOGIN_UI_VENDOR_TAG
#
# Behavior:
#   1. Loads any existing image-tags.env from origin/deploy, but per-key only
#      where the caller hasn't already supplied a value.
#   2. Force-creates a fresh `deploy` branch at master HEAD.
#   3. Writes image-tags.env recording the final pinned tags.
#   4. Sed-rewrites docker-compose.yml so every `<image>:latest` default
#      becomes `<image>:<pinned-tag>`.
#   5. Commits and force-pushes deploy.
#
set -euo pipefail

# --- 1. Hydrate from existing deploy-branch state (without clobbering caller).
git fetch origin deploy 2>/dev/null || true
if git rev-parse --verify origin/deploy >/dev/null 2>&1; then
    EXISTING="$(git show origin/deploy:image-tags.env 2>/dev/null || true)"
    if [ -n "$EXISTING" ]; then
        while IFS='=' read -r key value; do
            case "$key" in
                ''|'#'*) continue ;;
            esac
            current="$(eval "echo \${$key:-__unset__}")"
            if [ "$current" = "__unset__" ]; then
                export "$key=$value"
            fi
        done <<<"$EXISTING"
    fi
fi

# --- 2. Final fallback: ":latest" for any tag we still don't have.
: "${ORY_CONSENT_TAG:=latest}"
: "${ORY_INVITE_TAG:=latest}"
: "${ORY_KRATOS_CONFIG_TAG:=latest}"
: "${KRATOS_VENDOR_TAG:=latest}"
: "${HYDRA_VENDOR_TAG:=latest}"
: "${LOGIN_UI_VENDOR_TAG:=latest}"

echo "Pinning deploy branch to:"
echo "  ory-consent       = $ORY_CONSENT_TAG"
echo "  ory-invite        = $ORY_INVITE_TAG"
echo "  ory-kratos-config = $ORY_KRATOS_CONFIG_TAG"
echo "  kratos-vendor     = $KRATOS_VENDOR_TAG"
echo "  hydra-vendor      = $HYDRA_VENDOR_TAG"
echo "  login-ui-vendor   = $LOGIN_UI_VENDOR_TAG"

# --- 3. Materialize the deploy branch at master HEAD.
git config user.name  "GitHub Actions Bot"
git config user.email "actions@github.com"
git checkout -B deploy

# --- 4. Write the recorded state.
cat >image-tags.env <<EOF
# Auto-generated by .github/scripts/build-deploy-branch.sh.
# Records the concrete GHCR tags this deploy branch's docker-compose.yml
# is pinned to. Each workflow run reads the prior state, overrides only the
# tags it produced, and rewrites this file + docker-compose.yml.
ORY_CONSENT_TAG=$ORY_CONSENT_TAG
ORY_INVITE_TAG=$ORY_INVITE_TAG
ORY_KRATOS_CONFIG_TAG=$ORY_KRATOS_CONFIG_TAG
KRATOS_VENDOR_TAG=$KRATOS_VENDOR_TAG
HYDRA_VENDOR_TAG=$HYDRA_VENDOR_TAG
LOGIN_UI_VENDOR_TAG=$LOGIN_UI_VENDOR_TAG
EOF

# --- 5. Pin docker-compose.yml. Match only the `:latest` defaults present in
#       master; if someone manually edited compose to use a different tag,
#       leave it alone.
sed -i \
    -e "s|ory-consent:latest|ory-consent:$ORY_CONSENT_TAG|g" \
    -e "s|ory-invite:latest|ory-invite:$ORY_INVITE_TAG|g" \
    -e "s|ory-kratos-config:latest|ory-kratos-config:$ORY_KRATOS_CONFIG_TAG|g" \
    -e "s|kratos-vendor:latest|kratos-vendor:$KRATOS_VENDOR_TAG|g" \
    -e "s|hydra-vendor:latest|hydra-vendor:$HYDRA_VENDOR_TAG|g" \
    -e "s|kratos-selfservice-ui-node-vendor:latest|kratos-selfservice-ui-node-vendor:$LOGIN_UI_VENDOR_TAG|g" \
    docker-compose.yml

# --- 6. Commit + force-push.
git add image-tags.env docker-compose.yml
if git diff --cached --quiet; then
    echo "No changes to deploy branch — pushing anyway to retrigger Portainer."
fi
git commit --allow-empty \
    -m "pin: consent=$ORY_CONSENT_TAG invite=$ORY_INVITE_TAG kratos-config=$ORY_KRATOS_CONFIG_TAG kratos=$KRATOS_VENDOR_TAG hydra=$HYDRA_VENDOR_TAG login-ui=$LOGIN_UI_VENDOR_TAG"
git push origin deploy --force
